I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 229, in script
    if eksplor == 1:
  File "game/script.rpy", line 229, in <module>
    if eksplor == 1:
NameError: name 'eksplor' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 229, in script
    if eksplor == 1:
  File "F:\renpy-8.3.7-sdk\renpy\ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "F:\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "F:\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 229, in <module>
    if eksplor == 1:
NameError: name 'eksplor' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
ITS UTBK Simulator 1.0
Mon Apr 28 11:58:12 2025
